services:

    leankoalaintegration.zaproxy.init:
        class: LeanKoala\Integration\ZAProxyBundle\EventListener\IntegrationListener
        arguments: [ @service_container ]
        tags:
            - { name: 'kernel.event_listener', event: 'koalamon.integration.init', method: onInit }