leankoala_integration_smoke_config_project:
    path:     /p/{project}/integrations/smoke/config/
    defaults: { _controller: LeanKoalaIntegrationSmokeBundle:Config:project }

leankoala_integration_smoke_config:
    path:     /p/integrations/smoke/config/
    defaults: { _controller: LeanKoalaIntegrationSmokeBundle:Config:index }

# RegExExists

leankoala_integration_smoke_reg_ex_exists_homepage:
    path:     /p/{project}/integrations/smoke/regex/
    defaults: { _controller: LeanKoalaIntegrationSmokeBundle:RegExExists:index }

leankoala_integration_smoke_reg_ex_exists_store:
    path:     /p/{project}/integrations/smoke/regex/store
    defaults: { _controller: LeanKoalaIntegrationSmokeBundle:RegExExists:store }

# LittleSEO

leankoala_integration_smoke_seo_homepage:
    path:     /p/{project}/integrations/smoke/seo/
    defaults: { _controller: LeanKoalaIntegrationSmokeBundle:LittleSeo:index }

leankoala_integration_smoke_seo_store:
    path:     /p/{project}/integrations/smoke/seo/store
    defaults: { _controller: LeanKoalaIntegrationSmokeBundle:LittleSeo:store }

# XPath Checker

leankoala_integration_smoke_xpath_homepage:
    path:     /p/{project}/integrations/smoke/xpath/
    defaults: { _controller: LeanKoalaIntegrationSmokeBundle:XPathChecker:index }

leankoala_integration_smoke_xpath_store:
    path:     /p/{project}/integrations/smoke/xpath/store
    defaults: { _controller: LeanKoalaIntegrationSmokeBundle:XPathChecker:store }


# Json Validator

leankoala_integration_smoke_json_homepage:
    path:     /p/{project}/integrations/smoke/json/
    defaults: { _controller: LeanKoalaIntegrationSmokeBundle:JsonValidator:index }

leankoala_integration_smoke_json_store:
    path:     /p/{project}/integrations/smoke/json/store
    defaults: { _controller: LeanKoalaIntegrationSmokeBundle:JsonValidator:store }

# Http Head Check

leankoala_integration_smoke_http_head_homepage:
    path:     /p/{project}/integrations/smoke/httphead/
    defaults: { _controller: LeanKoalaIntegrationSmokeBundle:HttpHead:index }

leankoala_integration_smoke_http_head_store:
    path:     /p/{project}/integrations/smoke/httphead/store
    defaults: { _controller: LeanKoalaIntegrationSmokeBundle:HttpHead:store }

# Https Cert Check

leankoala_integration_smoke_https_cert_homepage:
    path:     /p/{project}/integrations/smoke/httpscert/
    defaults: { _controller: LeanKoalaIntegrationSmokeBundle:HttpsCert:index}

leankoala_integration_smoke_https_cert_store:
    path:     /p/{project}/integrations/smoke/httpscert/store
    defaults: { _controller: LeanKoalaIntegrationSmokeBundle:HttpsCert:store }